#!/usr/bin/env ruby
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs =  " -r irb/completion"
libs <<  " -r #{File.dirname(__FILE__) + '/../lib/appsta.rb'}"
puts "Loading appsta gem"
exec "#{irb} #{libs} --simple-prompt"